FROM node:20

WORKDIR /app

COPY package*.json tsconfig.json ./

COPY prisma ./prisma

# COPY  nginx.conf ./home/ej_tech/projects/nginx-crash-course/nginx.conf

RUN npm install

COPY . .

RUN npx prisma generate


EXPOSE 8000

CMD ["npm", "run", "dev"]