# Main context (this is the global configuration)
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Define NGINX rate limit zone (10MB memory pool, max 10 requests/sec per IP)
    limit_req_zone $binary_remote_addr zone=global_ip_limit:10m rate=10r/s;
    limit_req_status 429; # Return HTTP 429 (Too Many Requests) instead of default 503


    ## Upstream block pointing to Docker service names and internal port 8000
    upstream nodejs_cluster {
        keepalive 32;
        server app1:8000 max_fails=3 fail_timeout=10s;
        server app2:8000 max_fails=3 fail_timeout=10s;
        server app3:8000 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;
        # listen 443 ssl;  # Listen on port 448 for HTTPS
        # server_name localhost;

        # # SSL certificate settings
        # ssl_certificate /Users/nana/nginx-certs/nginx-selfsigned.crt;
        # ssl_certificate_key /Users/nana/nginx-certs/nginx-selfsigned.key;

        # Proxying requests to Node.js cluster
        location / {
            # Protect Node.js from volumetric bursts
            limit_req zone=global_ip_limit burst=20 nodelay;

            # Enable Docker's embedded DNS server for dynamic IP resolution
            resolver 127.0.0.11 valid=10s ipv6=off;

            proxy_pass http://nodejs_cluster;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Connection "";

            # REQUIRED FOR EXPRESS TRUST PROXY:
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

   
}
